# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/USTC/21spring books/Computer Organization/cod2021sp/lab5/pipeline_vivado/pipeline_vivado.srcs/sources_1/ip/DMem/DMem.xci
# IP: The module: 'DMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/USTC/21spring books/Computer Organization/cod2021sp/lab5/pipeline_vivado/pipeline_vivado.srcs/sources_1/ip/DMem/DMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/USTC/21spring books/Computer Organization/cod2021sp/lab5/pipeline_vivado/pipeline_vivado.srcs/sources_1/ip/DMem/DMem.xci
# IP: The module: 'DMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/USTC/21spring books/Computer Organization/cod2021sp/lab5/pipeline_vivado/pipeline_vivado.srcs/sources_1/ip/DMem/DMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
